name: "HackClubMC"  # TODO
version: "${project.version}"
main: "io.github.wlhackclub.hackclubmc.Main"  # TODO
api-version: "1.19"  # TODO


commands:
  givegun:
    description: "give a gun"
    usage: "/givegun"
    permission: "hackclubmc.all"
    permission-message: "not allowed L ratio bozo"
  givewarpdrive:
    description: "give a warp drive"
    usage: "/givewarpdrive"
    permission: "hackclubmc.all"
    permission-message: "not allowed L ratio bozo"
  givehyperion:
    description: "give a hyperion"
    usage: "/givehyperion"
    permission: "hackclubmc.all"
    permission-message: "not allowed L ratio bozo"


permissions:
  hackclubmc.all:
    default: op
