name: "HackClubMC"  # TODO
version: "${project.version}"
main: "io.github.wlhackclub.hackclubmc.Main"  # TODO
api-version: "1.19"  # TODO


#commands:
#  hackclubmc:
#    description: "..."
#    usage: "..."
#    permission: "hackclubmc.all"
#    permission-message: "..."


#permissions:
#  hackclubmc.all:
#    default: op
